<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
		
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"物资管理",
                        "menuJump":"列表",
                        "tableName":"goods"
                    }
                ],
                "menu":"物资管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"出入库订单管理",
                        "menuJump":"列表",
                        "tableName":"inOutOrder"
                    }
                ],
                "menu":"出入库订单管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                        ],
                        "menu":"出入库订单详情管理",
                        "menuJump":"列表",
                        "tableName":"inOutOrderList"
                    }
                ],
                "menu":"出入库订单详情管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"委托出入库订单管理",
                        "menuJump":"列表",
                        "tableName":"entrustInOutOrder"
                    }
                ],
                "menu":"委托出入库订单管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                        ],
                        "menu":"委托出入库订单详情管理",
                        "menuJump":"列表",
                        "tableName":"entrustInOutOrderList"
                    }
                ],
                "menu":"委托出入库订单详情管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"留言管理",
                        "menuJump":"列表",
                        "tableName":"liuyanxinxi"
                    }
                ],
                "menu":"留言管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"物品种类管理",
                        "menuJump":"列表",
                        "tableName":"dictionary"
                    }
                ],
                "menu":"物品种类管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,{
        "backMenu":[
		
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"委托出入库订单管理",
                        "menuJump":"列表",
                        "tableName":"entrustInOutOrder"
                    }
                ],
                "menu":"委托出入库订单管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                        ],
                        "menu":"委托出入库订单详情管理",
                        "menuJump":"列表",
                        "tableName":"entrustInOutOrderList"
                    }
                ],
                "menu":"委托出入库订单详情管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增"
                        ],
                        "menu":"留言管理",
                        "menuJump":"列表",
                        "tableName":"liuyanxinxi"
                    }
                ],
                "menu":"留言管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
